
package tarea02;

/**
 *
 * @author Marcel
 */
public class FrmHerencia extends javax.swing.JFrame {

    /** Creates new form FrmHerencia */
    public FrmHerencia() {
        initComponents();
        JpAlumno.setVisible(false);
        JpProfesor.setVisible(false);
        JpRAlumno.setVisible(false);
        JpRProfesor.setVisible(false);
        
      
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        jLabel1 = new javax.swing.JLabel();
        CmbSelecione = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TxtNombre = new javax.swing.JTextField();
        TxtApellidos = new javax.swing.JTextField();
        TxtEdad = new javax.swing.JTextField();
        TxtSexo = new javax.swing.JTextField();
        BtnAlumnoPresencial = new javax.swing.JButton();
        BtnAlumnoAdistancia = new javax.swing.JButton();
        BtnProfesorTCompleto = new javax.swing.JButton();
        BtnProfesorTParcial = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        LbNombre = new javax.swing.JLabel();
        LbApellidos = new javax.swing.JLabel();
        LbEdad = new javax.swing.JLabel();
        LbSexo = new javax.swing.JLabel();
        JpAlumno = new javax.swing.JPanel();
        TxtAcodigo = new javax.swing.JTextField();
        TxtANcursos = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        CmbEscuela = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        TxtSemestre = new javax.swing.JTextField();
        JpProfesor = new javax.swing.JPanel();
        TxtCProfesor = new javax.swing.JTextField();
        TxtPnCursos = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        CmbCaDictar1 = new javax.swing.JComboBox<>();
        JpRAlumno = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        lbCodigoAlumno = new javax.swing.JLabel();
        LbEscuelaAlumno = new javax.swing.JLabel();
        LbNCAlumno = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        LbSemetre = new javax.swing.JLabel();
        JpRProfesor = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        LbCodigoProfesor = new javax.swing.JLabel();
        LbNCursosProfesor = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        LbCursoaDictar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("DATOS GENERLES DE LA PERSONA");

        CmbSelecione.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Alumno Presencial", "Alumno Adistancia", "Profesor TParcial", "Profesor TCompleto", " " }));
        CmbSelecione.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmbSelecioneActionPerformed(evt);
            }
        });

        jLabel3.setText("Nombre    :");

        jLabel2.setText("Seleccione :");

        jLabel4.setText("Apellidos  :");

        jLabel5.setText("Edad        :");

        jLabel6.setText("Sexo         :");

        BtnAlumnoPresencial.setText("Alumno Presencial");
        BtnAlumnoPresencial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAlumnoPresencialActionPerformed(evt);
            }
        });

        BtnAlumnoAdistancia.setText("Alumno Adistancia");
        BtnAlumnoAdistancia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAlumnoAdistanciaActionPerformed(evt);
            }
        });

        BtnProfesorTCompleto.setText("Profesor Tiempo completo");
        BtnProfesorTCompleto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnProfesorTCompletoActionPerformed(evt);
            }
        });

        BtnProfesorTParcial.setText("Profesor Tiempo Parcial");
        BtnProfesorTParcial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnProfesorTParcialActionPerformed(evt);
            }
        });

        jLabel17.setText("DATOS DE LA PERSONA");

        jLabel8.setText("Nombre    :");

        jLabel18.setText("DATOS SEGUN SELECCIONADO");

        jLabel9.setText("Apellidos  :");

        jLabel10.setText("Sexo         :");

        jLabel11.setText("Edad        :");

        jLabel12.setText("Procesos que puede realizar la persona");

        LbNombre.setText("jLabel13");

        LbApellidos.setText("jLabel13");

        LbEdad.setText("jLabel13");

        LbSexo.setText("jLabel13");

        jLabel16.setText("Escuela                     :");

        CmbEscuela.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escuela Profesional de Medicina Veterinaria", "Escuela Profesional de Ingeniería de Agronegocios", "Escuela Profesional de Ingeniería Zootécnica", "Facultad de Medicina Humana y Ciencias de la Salud\t", "Escuela Profesional de Estomatología", "Escuela Profesional de Enfermería", "Escuela Profesional de Farmacia y Bioquímica", "Escuela Profesional de Medicina Humana", "Escuela Profesional de Nutrición Humana", "Escuela Profesional de Obstetricia", "Escuela Profesional de Psicología Humana", "Escuela Profesional de Tecnología Médica", "Escuela Profesional de Gerontología", "Facultad de Ciencias Empresariales\t", "Escuela Profesional de Administración y Negocios Internacionales", "Escuela Profesional de  Turismo, Hotelería y Gastronomía", "Escuela Profesional de Economía", "Escuela Profesional de Ciencias Contables y Financieras", "Facultad de Ciencias de la Comunicación, Educación y Humanidades\t", "Escuela Profesional de Ciencias de la Comunicación", "Escuela Profesional de Educación", "Escuela Profesional de Ciencias del Deporte", "Facultad de Derecho y Ciencia Política Derecho", "Facultad de Ingenierías y Arquitectura\t", "Escuela Profesional de Ingeniería de Sistemas e Informática", "Escuela Profesional de Ingeniería Electrónica y Telecomunicaciones", "Escuela Profesional de Ingeniería Mecánica", "Escuela Profesional de Ingeniería Industrial", "Escuela Profesional de Ingeniería Ambiental", "Escuela Profesional de Ingeniería Civil", "Escuela Profesional de Ingeniería de Minas", "Escuela Profesional de Arquitectura", "Escuela Profesional de Ingeniería Aeronáutica" }));

        jLabel7.setText("Codigo Alumno          :");

        jLabel13.setText("Nº de Cursos            :");

        jLabel24.setText("Semestre");

        javax.swing.GroupLayout JpAlumnoLayout = new javax.swing.GroupLayout(JpAlumno);
        JpAlumno.setLayout(JpAlumnoLayout);
        JpAlumnoLayout.setHorizontalGroup(
            JpAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpAlumnoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JpAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JpAlumnoLayout.createSequentialGroup()
                        .addGroup(JpAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JpAlumnoLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TxtAcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(JpAlumnoLayout.createSequentialGroup()
                                .addGroup(JpAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel24))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(JpAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TxtSemestre, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                                    .addComponent(TxtANcursos))))
                        .addContainerGap(128, Short.MAX_VALUE))
                    .addGroup(JpAlumnoLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CmbEscuela, 0, 1, Short.MAX_VALUE))))
        );
        JpAlumnoLayout.setVerticalGroup(
            JpAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpAlumnoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JpAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(TxtAcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JpAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CmbEscuela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(JpAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(TxtANcursos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JpAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(TxtSemestre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel14.setText("Codigo Profesor");

        jLabel15.setText("Nº Cursos a dictar");

        jLabel27.setText("Curso a Dictar");

        CmbCaDictar1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Programacion", "Matematicas", "Algoritmos", "Estadistica", " " }));

        javax.swing.GroupLayout JpProfesorLayout = new javax.swing.GroupLayout(JpProfesor);
        JpProfesor.setLayout(JpProfesorLayout);
        JpProfesorLayout.setHorizontalGroup(
            JpProfesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpProfesorLayout.createSequentialGroup()
                .addGroup(JpProfesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JpProfesorLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel15))
                    .addGroup(JpProfesorLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(JpProfesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel27)
                            .addComponent(jLabel14))))
                .addGap(51, 51, 51)
                .addGroup(JpProfesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TxtPnCursos)
                    .addComponent(TxtCProfesor)
                    .addComponent(CmbCaDictar1, 0, 191, Short.MAX_VALUE))
                .addContainerGap())
        );
        JpProfesorLayout.setVerticalGroup(
            JpProfesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JpProfesorLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(JpProfesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(TxtCProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(JpProfesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(CmbCaDictar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JpProfesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(TxtPnCursos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel19.setText("Codigo Del Alumno");

        jLabel20.setText("Escuela");

        jLabel21.setText("N° de Cursos");

        lbCodigoAlumno.setText("jLabel22");

        LbEscuelaAlumno.setText("jLabel23");

        LbNCAlumno.setText("jLabel24");

        jLabel25.setText("Semestre ");

        LbSemetre.setText("jLabel26");

        javax.swing.GroupLayout JpRAlumnoLayout = new javax.swing.GroupLayout(JpRAlumno);
        JpRAlumno.setLayout(JpRAlumnoLayout);
        JpRAlumnoLayout.setHorizontalGroup(
            JpRAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpRAlumnoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JpRAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(JpRAlumnoLayout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LbNCAlumno))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JpRAlumnoLayout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LbEscuelaAlumno))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JpRAlumnoLayout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(56, 56, 56)
                        .addComponent(lbCodigoAlumno))
                    .addGroup(JpRAlumnoLayout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LbSemetre)))
                .addContainerGap(179, Short.MAX_VALUE))
        );
        JpRAlumnoLayout.setVerticalGroup(
            JpRAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpRAlumnoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JpRAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(lbCodigoAlumno))
                .addGap(18, 18, 18)
                .addGroup(JpRAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(LbEscuelaAlumno))
                .addGap(18, 18, 18)
                .addGroup(JpRAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(LbNCAlumno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JpRAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(LbSemetre))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel22.setText("Codigo del Profesor");

        jLabel23.setText("N° de Cursos a Dictar");

        LbCodigoProfesor.setText("jLabel24");

        LbNCursosProfesor.setText("jLabel25");

        jLabel26.setText("Curso a Dictar");

        LbCursoaDictar.setText("jLabel28");

        javax.swing.GroupLayout JpRProfesorLayout = new javax.swing.GroupLayout(JpRProfesor);
        JpRProfesor.setLayout(JpRProfesorLayout);
        JpRProfesorLayout.setHorizontalGroup(
            JpRProfesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpRProfesorLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(JpRProfesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(JpRProfesorLayout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LbNCursosProfesor))
                    .addGroup(JpRProfesorLayout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addGap(72, 72, 72)
                        .addComponent(LbCodigoProfesor))
                    .addGroup(JpRProfesorLayout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LbCursoaDictar)))
                .addContainerGap(151, Short.MAX_VALUE))
        );
        JpRProfesorLayout.setVerticalGroup(
            JpRProfesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpRProfesorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JpRProfesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(LbCodigoProfesor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(JpRProfesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(LbCursoaDictar))
                .addGap(18, 18, 18)
                .addGroup(JpRProfesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(LbNCursosProfesor))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TxtNombre)
                                    .addComponent(TxtApellidos)
                                    .addComponent(CmbSelecione, 0, 151, Short.MAX_VALUE))
                                .addGap(156, 156, 156)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TxtEdad)
                                    .addComponent(TxtSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(BtnAlumnoPresencial)
                                        .addGap(55, 55, 55)
                                        .addComponent(BtnAlumnoAdistancia))
                                    .addComponent(JpAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(54, 54, 54)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(JpProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(BtnProfesorTCompleto)
                                        .addGap(104, 104, 104)
                                        .addComponent(BtnProfesorTParcial, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(332, 332, 332)
                        .addComponent(jLabel17))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(341, 341, 341)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(378, 378, 378)
                        .addComponent(jLabel18))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel9)
                                .addComponent(jLabel8))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel10))))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LbSexo)
                            .addComponent(LbEdad)
                            .addComponent(LbNombre)
                            .addComponent(LbApellidos))
                        .addGap(86, 86, 86)
                        .addComponent(JpRAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JpRProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(331, 331, 331)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(TxtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(TxtSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(TxtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CmbSelecione, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(15, 15, 15)
                .addComponent(jLabel18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(JpAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(JpProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnAlumnoPresencial)
                    .addComponent(BtnAlumnoAdistancia)
                    .addComponent(BtnProfesorTCompleto)
                    .addComponent(BtnProfesorTParcial))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(LbNombre))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(LbApellidos))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(LbEdad))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(LbSexo)))
                    .addComponent(JpRProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JpRAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addContainerGap())
        );

        pack();
    }//GEN-END:initComponents

    private void BtnAlumnoPresencialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAlumnoPresencialActionPerformed
        CHPAlumnoPresencial AlumnoPresencial;
        AlumnoPresencial = new CHPAlumnoPresencial();
        AlumnoPresencial.CHPersona( TxtNombre.getText(), TxtApellidos.getText(), Integer.parseInt(TxtEdad.getText()), TxtSexo.getText());
        AlumnoPresencial.mostrar_Persona(LbNombre,LbApellidos,LbEdad,LbSexo);
        AlumnoPresencial.DatosAlumno(TxtAcodigo.getText(),Integer.parseInt(TxtANcursos.getText()) , TxtSemestre.getText(), CmbEscuela.getSelectedItem().toString());
        AlumnoPresencial.MostrarDatos(lbCodigoAlumno,LbEscuelaAlumno,LbNCAlumno,LbSemetre);
        
        //persona.Ingresar_persona(TxtCodigo.getText(), TxtNombre.getText(), TxtApellidos.getText(), Integer.parseInt(TxtEdad.getText()), TxtSexo.getText());
        
        JpRAlumno.setVisible(true);
    }//GEN-LAST:event_BtnAlumnoPresencialActionPerformed

    private void CmbSelecioneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmbSelecioneActionPerformed
        // TODO add your handling code here:
        if (null!=CmbSelecione.getSelectedItem().toString())
               // TODO add your handling code here:
               switch (CmbSelecione.getSelectedItem().toString()) {
               case "Alumno Presencial":
                      JpAlumno.setVisible(true);
                     JpProfesor.setVisible(false);
               break;
                   case "Alumno Adistancia":
                       JpAlumno.setVisible(true);
                      JpProfesor.setVisible(false);
                   break;
                   case "Profesor TParcial":
                       JpProfesor.setVisible(true);
                       JpAlumno.setVisible(false);
                   break;
                   case "Profesor TCompleto":
                       JpProfesor.setVisible(true);
                       JpAlumno.setVisible(false);
                   break;
               default:
               break;
               }
           
    }//GEN-LAST:event_CmbSelecioneActionPerformed

    private void BtnAlumnoAdistanciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAlumnoAdistanciaActionPerformed
        // TODO add your handling code here:
        CHPAlumnoAdistancia alumnoAdistancia= new CHPAlumnoAdistancia();
        alumnoAdistancia.CHPersona( TxtNombre.getText(), TxtApellidos.getText(), Integer.parseInt(TxtEdad.getText()), TxtSexo.getText());
        alumnoAdistancia.mostrar_Persona(LbNombre, LbApellidos, LbEdad, LbSexo);
        
        alumnoAdistancia.DatosAlumno(TxtAcodigo.getText(),Integer.parseInt(TxtANcursos.getText()) , TxtSemestre.getText(), CmbEscuela.getSelectedItem().toString());
        alumnoAdistancia.MostrarDatos(lbCodigoAlumno,LbEscuelaAlumno,LbNCAlumno,LbSemetre);
        
        
        JpRAlumno.setVisible(true);
    }//GEN-LAST:event_BtnAlumnoAdistanciaActionPerformed

    private void BtnProfesorTCompletoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnProfesorTCompletoActionPerformed
        // TODO add your handling code here:
        CHPProfesorTCompleto ProfesorTCompleto= new CHPProfesorTCompleto();
        ProfesorTCompleto.CHPersona( TxtNombre.getText(), TxtApellidos.getText(), Integer.parseInt(TxtEdad.getText()), TxtSexo.getText());
        ProfesorTCompleto.mostrar_Persona(LbNombre, LbApellidos, LbEdad, LbSexo);
        
        ProfesorTCompleto.DatosProfesor(TxtCProfesor.getText(), CmbCaDictar1.getSelectedItem().toString(),TxtPnCursos.getText());
        ProfesorTCompleto.mostarDatos(LbCodigoProfesor,LbCursoaDictar,LbNCursosProfesor);
        
        
        JpRProfesor.setVisible(true);
    }//GEN-LAST:event_BtnProfesorTCompletoActionPerformed

    private void BtnProfesorTParcialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnProfesorTParcialActionPerformed
        // TODO add your handling code here:
        CHPProfesorTParcial ProfesorTParcial= new CHPProfesorTParcial();
        ProfesorTParcial.CHPersona( TxtNombre.getText(), TxtApellidos.getText(), Integer.parseInt(TxtEdad.getText()), TxtSexo.getText());
        ProfesorTParcial.mostrar_Persona(LbNombre, LbApellidos, LbEdad, LbSexo);
        
        ProfesorTParcial.DatosProfesor(TxtCProfesor.getText(), CmbCaDictar1.getSelectedItem().toString(),TxtPnCursos.getText());
        ProfesorTParcial.mostarDatos(LbCodigoProfesor,LbCursoaDictar,LbNCursosProfesor);
        JpRProfesor.setVisible(true);
    }//GEN-LAST:event_BtnProfesorTParcialActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing
                                                                   .UIManager
                                                                   .getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing
                         .UIManager
                         .setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util
                .logging
                .Logger
                .getLogger(FrmHerencia.class.getName())
                .log(java.util
                         .logging
                         .Level
                         .SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util
                .logging
                .Logger
                .getLogger(FrmHerencia.class.getName())
                .log(java.util
                         .logging
                         .Level
                         .SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util
                .logging
                .Logger
                .getLogger(FrmHerencia.class.getName())
                .log(java.util
                         .logging
                         .Level
                         .SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util
                .logging
                .Logger
                .getLogger(FrmHerencia.class.getName())
                .log(java.util
                         .logging
                         .Level
                         .SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt
            .EventQueue
            .invokeLater(new Runnable() {
                public void run() {
                    new FrmHerencia().setVisible(true);
                }
            });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAlumnoAdistancia;
    private javax.swing.JButton BtnAlumnoPresencial;
    private javax.swing.JButton BtnProfesorTCompleto;
    private javax.swing.JButton BtnProfesorTParcial;
    private javax.swing.JComboBox<String> CmbCaDictar1;
    private javax.swing.JComboBox<String> CmbEscuela;
    private javax.swing.JComboBox<String> CmbSelecione;
    private javax.swing.JPanel JpAlumno;
    private javax.swing.JPanel JpProfesor;
    private javax.swing.JPanel JpRAlumno;
    private javax.swing.JPanel JpRProfesor;
    private javax.swing.JLabel LbApellidos;
    private javax.swing.JLabel LbCodigoProfesor;
    private javax.swing.JLabel LbCursoaDictar;
    private javax.swing.JLabel LbEdad;
    private javax.swing.JLabel LbEscuelaAlumno;
    private javax.swing.JLabel LbNCAlumno;
    private javax.swing.JLabel LbNCursosProfesor;
    private javax.swing.JLabel LbNombre;
    private javax.swing.JLabel LbSemetre;
    private javax.swing.JLabel LbSexo;
    private javax.swing.JTextField TxtANcursos;
    private javax.swing.JTextField TxtAcodigo;
    private javax.swing.JTextField TxtApellidos;
    private javax.swing.JTextField TxtCProfesor;
    private javax.swing.JTextField TxtEdad;
    private javax.swing.JTextField TxtNombre;
    private javax.swing.JTextField TxtPnCursos;
    private javax.swing.JTextField TxtSemestre;
    private javax.swing.JTextField TxtSexo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lbCodigoAlumno;
    // End of variables declaration//GEN-END:variables

}
